-- REDACTED: This migration originally contained a hardcoded PII encryption key.
-- The key has been rotated (2026-04-08) and now lives exclusively in Supabase Vault
-- (vault.secrets, name = 'pii_encryption_key').
-- The current encrypt_pii/decrypt_pii functions are defined in migration
-- 20260405150001_encryption_key_from_vault.sql and read from Vault at runtime.
--
-- This migration has already been applied to all environments. The functions it
-- created have been superseded by later migrations. No action needed.
